### ISSUE TITLE
20103 - no need to push if using map()

### ISSUE THREAD

**Issue by ynotrusso** [hschong/Tortuga#1]
https://github.com/hschong/Tortuga/blob/2a6afc6a68c5e06f3eb2faa001821312e20b4078/k-02.js#L16

**Comment by hschong** [comment]
Fixed as below

let plusOne = (element) => ++element
let makeNewArray = (array, func) => array.map(func)
let newNumbers = makeNewArray(numbers, plusOne)
console.log(newNumbers)

**Comment by hschong** [comment]
console.log('#20103 ===> ', numbers.map((element)=>element+1))
