### ISSUE TITLE
20203 - invalid

### ISSUE THREAD

**Issue by ynotrusso** [hschong/Tortuga#2]
https://github.com/hschong/Tortuga/blob/2a6afc6a68c5e06f3eb2faa001821312e20b4078/k-02.js#L129

**Comment by hschong** [comment]
Fixed as below

let getRoundNumber = (number, decimals) => {
  if (decimals === undefined ) {
    return Math.round(number)
  } else {
    return number.toFixed(decimals)
  }
}
console.log(getRoundNumber(1013.34529, 2))
