### ISSUE TITLE
use class Receipt instead

### ISSUE THREAD

**Issue by ynotrusso** [hschong/Tortuga#4]
https://github.com/hschong/Tortuga/blob/91ad600b411dcedbe3db9331bcca24756362b236/k-02-class.js#L152

**Comment by hschong** [comment]
fixed as below:

let makeProductListAfterDiscounting = () => fruitNames.map((name, index) => {
    product = new Product(name, prices[index])
    product.applyDiscount(discounts[index])
    return product
})

let logReceipt = ()=> {
    console.log('#020504')
    receipt = new Receipt(makeProductListAfterDiscounting())
    console.log('Receipt: [')
    makeProductListAfterDiscounting().forEach(product => console.log(product))
    console.log(']')
    console.log(`Total: ${receipt.calcTotal()}`)
}

logReceipt()
